### ISSUE TITLE
Get effective permissions for specific user and node

### ISSUE THREAD

**Issue by loftux** [OrderOfTheBee/ootbee-support-tools#110]
### Use case
A user has set permissions and should have the rights to "Delete", "Write" etc, but something is not allowing the user to perform the action. To narrow down the issue, finding out the actual effective permission on that specific node for that user would help.

### Proposed solution
Form input
- username
- nodeRef
Output
List of low level permissions with true/false if the user has the permission.

Since this needs a runAs, the approach would be either a Java class to fetch this or implement a utility class for javascript to do the runAs (such as https://github.com/clegallic/alfresco-js-run-as-user). The second option would allow for reuse if needed in other support tools features when needed.

I can give this a shot if you find the idea worth implementing.

**Comment by AFaust** [comment]
Such a feature generally sounds like a valueable addition to the Support Tools. I have not given much thought yet to such small use cases where we might end up with dozens or hundreds of small purpose forms / tools. Off the top of my hat I'd love to have something extensible / reusable in terms of a frontend that does not clutter up the administration console too much. Maybe something along the lines of a tool like the workflow console that could be extended by small command interpreter scripts / classes.

As with the runAs support for JavaScript. I would prefer if the Support Tools does not provide any global JavaScript root objects, especially if those might be used to circumvent security or clash with other addons. Since all of our JavaScript code is loaded from the classpath we can make use of runAs without a special Script API extension by using the Rhino Java interop features.

```javascript
Packages.org.alfresco.repo.security.authentication.AuthenticationUtil.pushAuthentication();
Packages.org.alfresco.repo.security.authentication.AuthenticationUtil.setRunAsUser('mjackson')
try {
   // ... code ...
   Packages.org.alfresco.repo.security.authentication.AuthenticationUtil.popAuthentication();
} catch (e) {
   // ... code ...
   Packages.org.alfresco.repo.security.authentication.AuthenticationUtil.popAuthentication();
   throw e; // rethrow (optional / if relevant)
}
```

**Comment by AFaust** [comment]
@loftux / @binduwavell: I have added a basic command interpreter tool with an initial plugin for the permission check Loftux suggested.
![ootbee-support-tools - command console - permissions plugin](https://user-images.githubusercontent.com/2211521/41196341-c358797c-6c3d-11e8-8bb7-55e04c49be0e.png)

**Comment by AFaust** [comment]
I have enhanced the command console with another plugin to interact with subsystems (list / change properties / revert), as I had to test my configuration persistence mechanism functionality of the hack-a-thon project.

**Comment by binduwavell** [comment]
I just saw that the Minecraft team released there command java library. I wonder if it would be a good fit for this. Another MineCraft tie-in to Alfresco could never go wrong ;)

**Comment by binduwavell** [comment]
https://minecraft.net/en-us/article/programmers-play-minecrafts-inner-workings
