### ISSUE TITLE
Providing of metrics for Prometheus

### ISSUE THREAD

**Issue by andreaskring** [OrderOfTheBee/ootbee-support-tools#158]
## FEATURE / ENHANCEMENT

**Suggestion for a new feature capable of providing Alfresco metrics for Prometheus**

Prometheus (https://prometheus.io/) is a powerful open-source monitoring and alerting toolkit which can be used for e.g. monitoring any number of system parameters as they vary over time. The data harvested by Prometheus can easily be presented graphically very nicely by tools like e.g. Grafana (https://grafana.com/). 

The OOTB Support Tool provides a lot of important data which could be harvested by a tool like Prometheus which is dedicated for handling such time-series data. The format required by Prometheus is a simple `plain/text` format. For example, the active sessions data could served in Promethues format by adding the FTL file `src/main/resources/alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/active-sessions.get.text.ftl` with this content:
```
# HELP alfresco_active_sessions Number of active sessions
# TYPE alfresco_active_sessions gauge
alfresco_active_sessions{type="NumActive"} ${connectionPoolData.numActive?c}
alfresco_active_sessions{type="MaxActive"} ${connectionPoolData.maxActive?c}
alfresco_active_sessions{type="NumIdle"} ${connectionPoolData.numIdle?c}
alfresco_active_sessions{type="UserCountNonExpired"} ${userSessionData.userCountNonExpired?c}
alfresco_active_sessions{type="TicketCountNonExpired"} ${userSessionData.ticketCountNonExpired?c}
```

We are using Prometheus in the organization where I work, and I have a task at hand where I need to extract Alfresco session data into Prometheus - if this is of general interest, I can make a PR containing the above file? (instead of modifying my own forked version of the OOTB Support Tool).

The above can of course also be extended to serve other Alfresco metrics in the Prometheus format.

(edited by @AFaust to conform with our issue template)

**Comment by AFaust** [comment]
I fully support the idea of adding alternative response formats thta may be used in monitoring tools, and I would gladly see such contributions as PRs to this module.
One thing I would note though is that any response format we add - in addition to the plain HTML for our own UI and JSON for loading udpate data - should either be tooling-agnostic or provide a tool-agnostic default response with tool-specific responses activated by a URL query parameter. In this case this would mean that there should be a non-Prometheus default text response and a URL query parameter (e.g. via [&?]textResponseType=prometheus ) which toggles an if/elseif in the FTL to render the structure just like Prometheus requires it. The reason for this is that other people may want to add response variants for their specific tooling in the future, and I'd like to standardise on how this is handled in this module right from the beginning.

@binduwavell / @yregaieg / @ahmedowian I welcome any points of view you may want to provide.

**Comment by andreaskring** [comment]
As far as I understand, the output used by Prometheus is the de facto standard for transmitting metrics, i.e. https://openmetrics.io/ links to the Prometheus from their website an they say that "OpenMetrics is a working group to determine a standard for exposing metrics data, influenced by the Prometheus exposition format" (currently the two formats ). So instead of calling the output served by e.g. `src/main/resources/alfresco/templates/webscripts/org/orderofthebee/support-tools/admin/ootbee-support-tools/active-sessions.get.text.ftl` mentioned above for "a Prometheus format", it could be called "an Open Metrics format", which can be consider as a generic format. According to the discussion here https://github.com/OpenObservability/OpenMetrics/issues/137 , the Open Metrics standard is also going to be adapted by the Open Telemetry project (https://opentelemetry.io/) for the metrics part of their standard. 

So in order to go for "the low hanging fruits" (i.e. provide metrics data in the Open Metrics = Prometheus format) - would it make sense to just go for the simple FTL text files as the one above (as this is easy to implement) and since the Prometheus output can be considered - as I understand it - as a generic metrics output?

**Comment by AFaust** [comment]
Reading https://medium.com/@leodido/openmetrics-20d40eb0b302 there seems to be a registered content type / mimetype ```application/openmetrics-text``` for the OpenMetrics format. This would / could allow us to cleanly separate the OpenMetrics format from any (future?) more generic / arbitrary text format, e.g. have a ```active-sessions.get.omf.ftl``` (or similar) which is dedicated to that format. That would be perfect and Alfresco already supports such differentiations out of the box. I don't know how Prometheus calls any APIs that provide metrics, but if they provide an HTTP Accept header with the mimetype of ```application/openmetrics-text```, then we could rely on the web script framework negotiation mechanism to pick the right template.

Ok - I'd suggest you go ahead with the initial PR for a regular ```text/plain``` variant of the web script template, and we can deal with a dedicated mimetype-negotiated format in a subsequent GitHub issue / PR, so that we don't overload this one.

**Comment by yregaieg** [comment]
> I fully support the idea of adding alternative response formats that may be used in monitoring tools, and I would gladly see such contributions as PRs to this module.
> One thing I would note though is that any response format we add - in addition to the plain HTML for our own UI and JSON for loading udpate data - should either be tooling-agnostic or provide a tool-agnostic default response with tool-specific responses activated by a URL query parameter. In this case this would mean that there should be a non-Prometheus default text response and a URL query parameter (e.g. via [&?]textResponseType=prometheus ) which toggles an if/elseif in the FTL to render the structure just like Prometheus requires it. The reason for this is that other people may want to add response variants for their specific tooling in the future, and I'd like to standardise on how this is handled in this module right from the beginning.
> 
> @binduwavell / @yregaieg / @ahmedowian I welcome any points of view you may want to provide.

I think the tool-agnostic part to be a very persistent point, but I am definitely not in favor of using FTL for this, I would rather rely on micrometer which is capable to track down all sorts of metrics and export them into any of the popular metrics formats... and rely alfresco-global props to configure the format/metric-dialect....

I have actually started some effort into this area but then have stopped midway through due to priorities change, but I am willing to share my code for reuse/inspiration. What is currently missing is actually making everything configurable from the metrics collected, tags, or even the the registry used to determine the format, but it is in a working state.

**Comment by AFaust** [comment]
@yregaieg Since I was about to review the PR, just one observation / question: Having this "point-in-time" metrics retrieval via FTL-rendered text should in no way conflict with any micrometer use, right? So would there be any harm in including this now as an FTL-based feature while work continues on a micrometer / Java-requiring alternative? Additionally, using FTL fits generally better with the "as lightweight as possible" aim of Support Tools (while not explicitely stated, the [reivew criteria](https://github.com/OrderOfTheBee/ootbee-support-tools/blob/master/CONTRIBUTING.md#review-criteria) try to encourage that point).

**Comment by yregaieg** [comment]
Well, in theory it shouldn't really conflict, but once/if we roll out micrometer, the whole thing would become obsolete, as in a duplicate version, far more verbose code wise...
But I peaked at his PR and it looks neat, he didn't create new webscripts to expose the data, but reused the ones from admin-console and exposed them under a different format... So I only have a small request before accepting it: Would it be possible to document those endpoints somewhere maybe even expose a graphana dashboard or something ?

**Comment by andreaskring** [comment]
@yregaieg The FTL files include `# HELP` lines giving a short metrics descriptions. It is fine by me to provide more documentation, but I am not sure exactly which kind of documentation you have in mind?

Regarding the question about exposing a Grafana dashboard - do you mean providing Grafana dashboard configurations as JSON files? If so, I can create a few JSON configuration files.

**Comment by yregaieg** [comment]
Sorry for totally missing your last comment, I will merge this now, but please feel free to share some sample graphana dashboard or alike
