### ISSUE TITLE
[Feature Request] Add support for alfresco 7.4.0 and the new log4jv2 library

### ISSUE THREAD

**Issue by p4535992** [OrderOfTheBee/ootbee-support-tools#207]
## FEATURE / ENHANCEMENT

Starting from ACS 7.4, log4jv2 will be the library used for logging capabilities. 

Many parts of the code refer to the old log4j package version 1 unfortunately there would need to be an update of the references.

**Comment by AFaust** [comment]
I have seen the change to log4j2 when looking at the current master in the last couple of months. Adding support for the new library will take quite some work as we need to still support the old library for older Alfresco versions, lest we want to start having OOTBee Support Tools releases locked to an aggressive "mininum" ACS version. We currently support 5.0.d/5.1+ - while 5.x could be argued to not warrant continued support, we should keep any 6.x as supported. An example of multi-ACS-version support is the reworked Transformations tool, which supports all iterations from pre-6.x transformers over the intermediate states in 6.x up to the now stable 7.x transform service / RenditionService2

**Comment by p4535992** [comment]
Ty for your hard working.

**Comment by y-melo** [comment]
@AFaust, First, I'd like to thank you for the effort.  and ask:
Do you know when the updated version (compatible with 7.4) will be available?

**Comment by AFaust** [comment]
@y-melo Last weekend I finished tests and corrections for the Repository-tier module. Next up is Share-tier module, which should hopefully be significantly faster since I should be able to reuse a lot of the approaches / code. I hope to be done by end of month, and depending on reviewers, have a release in October.

**Comment by AFaust** [comment]
Share support for Log4J compatibility has been implemented and tested on pre-7.4 and 7.4. Due to Log4J2 having a different inheritance behaviour when it comes to runtime log level changes, there is a functional regression that still needs to be addressed somehow: any logger inheriting configuration from a parent logger has a decoupled internal runtime configuration object, and when the parent logger is altered, the loggers below it don't have their levels transparently altered as was the case in Log4J1.
