### ISSUE TITLE
Add a summary of features/screens to the README/wiki

### ISSUE THREAD

**Issue by binduwavell** [OrderOfTheBee/ootbee-support-tools#34]
Ideally we would explain to folks in words what they will receive if they install this add-on.

**Comment by AFaust** [comment]
Assigned to me since I have already have begun a couple of weeks ago. Tools are documented in the wiki with two overview pages ([Repository Tools](https://github.com/OrderOfTheBee/ootbee-support-tools/wiki/Repository%20Tools) and [Share Tool](https://github.com/OrderOfTheBee/ootbee-support-tools/wiki/Share%20Tools)) acting as entry points.
