### ISSUE TITLE
Artifact net.time4j:time4j-core:jar:3.23 could not be resolved

### ISSUE THREAD

**Issue by iwkse** [OrderOfTheBee/ootbee-support-tools#38]
Hi,
I'm trying to install the modules, compiling the repo one I received this error:
```
[ERROR] Failed to execute goal on project ootbee-support-tools-repo: Could not resolve dependencies for project org.orderofthebee.addons:ootbee-support-tools-repo:amp:0.0.1.0-SNAPSHOT: The following artifacts could not be resolved: net.time4j:time4j-core:jar:3.23, net.time4j:time4j-i18n:jar:3.23: Could not transfer artifact net.time4j:time4j-core:jar:3.23 from/to central (https://repo.maven.apache.org/maven2): GET request of: net/time4j/time4j-core/3.23/time4j-core-3.23.jar from central failed: Connection reset -> [Help 1]
```
Do you have idea why?

Nevermind. I find it out. It seems the share module must be compiled before the repo one. Following this order it goes fine

**Comment by AFaust** [comment]
Actually no. There is no compile order dependency between the Repository and the Share module. There only exists a runtime dependency since one of the tools (the Share-tier Log4J Settings page) relies on Repository-tier web scripts to be able to configure the loggers / access log files on that tier.

**Comment by iwkse** [comment]
True..I cleaned and rebuilt and now it just compiles. I don't know why.
