### ISSUE TITLE
Log snapshotting fearure

### ISSUE THREAD

**Issue by binduwavell** [OrderOfTheBee/ootbee-support-tools#57]
It would be amazing to be able to temporarily adjust loggers, for all log output to be siphoned off and then with the click of a button to restore the previous loggers and download a copy of the log statements that happened during the temporary adjustment in settings.

Users can use this to increase logging, perform a test and restore logging. The log file they receive will automatically bracket their test.

You could even add a lap timer feature like a stopwatch where the user can click a button to stamp out a log entry like "event 1" the next time they press the button "event 2" would be logged, etc. this way they could use this snapshot feature for a multi segment test and more easily find each part of their test in the log file.

**Comment by AFaust** [comment]
We already maintain a model of logging level changes in the background. It should be fairly straight-forward to combine such a model with a custom appender that logs to a file inside the temporary files folder, and combine the already existing reset and download features.

The activation of a log "snapshotting session" (new action) would register the appender to the root logger and all loggers with additivity set to false. It would also create a backup of the current logging level change model if any changes have been applied to the Log4J configuration before, so that the deactivation of the session will restore the configuration to the previous, effective state, not the state defined by the persistent configuration.
The custom log entries for demarcation of special log segments would be done via a non class-related top-level logger specific to that feature.
