### ISSUE TITLE
Add feature to clear (purge) caches

### ISSUE THREAD

**Issue by yregaieg** [OrderOfTheBee/ootbee-support-tools#70]
It can be really useful to be able to purge the content of a cache, either for dev/profiling reasons or when suspecting inconsistent values in the cache.
It is in my understanding that such operation on some caches can break Alfresco, so might be wise to limit this feature to the "safe to clear" caches, or display a disclaimer for confirmation before making the call to clear the cache.

**Comment by AFaust** [comment]
Since we may need to allow system administrators to limit some of the other functionality too (e.g. download/delete log files), we should introduce properties into alfresco-global.properties to determine what features are active, and potentially what elements these features can be applied on. In the case of caches we could use the cache configuration property format (cache.<name>.<property>) to add a "supportRuntimeClear" and/or "allowRuntimeClear" setting. We would have to pre-define the value for the out-of-the-box caches.

**Comment by AFaust** [comment]
Going to try doing this during BeeCon hack-a-thon today.
